# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=posts.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
